# .streamlit/config.toml

[server]
headless = true
runOnSave = true
port = 8501
enableCORS = true
enableXsrfProtection = true
folderWatchBlacklist = ["__pycache__", "*.pyc"]
fileWatcherType = "poll"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#034694"
secondaryBackgroundColor = "#f5f5f5"
font = "sans serif"
